sarahah/accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout


from .views import dashboard, register, settings, editProfile, changePassword, removeProfile

urlpatterns = [
    url(r'^$', dashboard, name="dashboard"),
    url(r'^login/$', login, {'template_name':'accounts/login.html'}, name="login"),
    url(r'^logout/$', logout, {'next_page':'core:home'}, name="logout"),
    url(r'^register/', register, name="register"),
    url(r'^settings/(?P<setting>[\w]+)/', settings, name="settings"),

    url(r'^edit/', editProfile, name="editProfile"),
    url(r'^cgdPassword/', changePassword, name="changePassword"),
    url(r'^rmvProfile/', removeProfile, name="removeProfile"),
]

sarahah/core/urls.py
from django.conf.urls import url, include

from .views import home, aboutus, contact


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about-us/$', aboutus, name='about'),
    url(r'^contact/$', contact, name='contact'),
]

sarahah/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from sarahah.core import urls as core
from sarahah.accounts import urls as accounts
from sarahah.smessages import urls as messages

from sarahah.accounts.views import pubProfile

urlpatterns = [
    url(r'', include(core, namespace="core")),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include(accounts, namespace="account")),
    url(r'messages/', include(messages, namespace="message")),
    url(r'^(?P<profile>[\w0-9_-]+)/$', pubProfile, name='pubProfile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sarahah/core/models.py
from django.db import models

# Create your models here.

sarahah/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    template_name = "index.html"
    return render(request, template_name)

def aboutus(request):
    template_name = "about_us.html"
    return render(request, template_name)

def contact(request):
    template_name = "contact.html"
    return render(request, template_name)

sarahah/core/templates/security/_menu.html
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'account:dashboard' %}">My Messages</a></li>
        <li><a href="{% url 'account:settings' 'profile' %}">Settings</a></li>
        <li><a href="{% url 'account:logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'account:login' %}">Login</a></li>
        <li><a href="{% url 'account:register' %}">Register</a></li>
        {% endif %}
        <li><a href="{% url 'core:about' %}">About Us</a></li>
        <li><a href="{% url 'core:contact' %}">Contact Us</a></li>
    </ul>
</div>
<!-- /.navbar-collapse -->