sarahah/core/urls.py
from django.conf.urls import url, include

from .views import home, aboutus, contact


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about-us/$', aboutus, name='about'),
    url(r'^contact/$', contact, name='contact'),
]

sarahah/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from sarahah.core import urls as core
from sarahah.accounts import urls as accounts
from sarahah.smessages import urls as messages

from sarahah.accounts.views import pubProfile

urlpatterns = [
    url(r'', include(core, namespace="core")),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include(accounts, namespace="account")),
    url(r'messages/', include(messages, namespace="message")),
    url(r'^(?P<profile>[\w0-9_-]+)/$', pubProfile, name='pubProfile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sarahah/core/models.py
from django.db import models

# Create your models here.

sarahah/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    template_name = "index.html"
    return render(request, template_name)

def aboutus(request):
    template_name = "about_us.html"
    return render(request, template_name)

def contact(request):
    template_name = "contact.html"
    return render(request, template_name)

sarahah/core/templates/about_us.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>About Us</h2>
    <p>Sarahah helps you in discovering your strengths and areas for improvement by receiving honest feedback from your employees
        and your friends in a private manner</p>

    <hr>

    <h2>FAQ</h2>
    <h3>Will Sarahah show the identity of senders?</h3>
    <p>Sarahah won't disclose the identity of the logged-in senders to users except with their consent.</p>
    <br>
    <h3>Is Sarahah a hacker?!</h3>
    <p>Sarahah doesn't steal data but websites and apps impersonating Sarahah could do that</p>
    <br>
    <h3>Can Sarahah visitors view my messages?</h3>
    <p>They can't as long as you don't share your messages</p>
    <br>
    <h3>Is there a Sarahah mobile app?</h3>
    <p>Yes, the official Sarahah app is on Google Play and App Store</p>
    <br>
    <h3>Can I respond to messages?</h3>
    <p>You can't respond to messages now. We are studying this option</p>
    <br>
</div>
{% endblock %}

sarahah/core/templates/base.html
{% load static bootstrap3 %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

        {% bootstrap_css %}
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                        aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                    <a class="navbar-brand" href="{% url 'core:home' %}">Saraha-Django</a>
                </div>

                {% include 'security/_menu.html' %}
            </div>
            <!-- /.container-fluid -->
        </nav>

        <div class="container-fluid">
            {% block content %}{% endblock %}
        </div>

        <footer class="fixed-footer">
            <p>Sarahah-Django 2017 ©</p>
        </footer>

        {% bootstrap_javascript 'jquery' %}
        {% block scripts %}{% endblock %}
    </body>
</html>

sarahah/core/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Contact Us</h2>
    <br><br>
    <p>To contact us by e-mail for non-support requests:</p>
    <p><a href="mailto:sarahah@sarahah.com">sarahah@sarahah.com</a></p>
    <p>Or through social networks below :)</p>
</div>
{% endblock %}

sarahah/core/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h2>Get honest feedback from your coworkers and friends</h2>

    <div class="row">
        <div class="col col-sm-12 col-md-6">
            <h3>At work</h3>
            <ul>
                <li>Enhance your areas of strength</li>
                <li>Strengthen Areas for Improvement</li>
            </ul>
        </div>
        <div class="col col-sm-12 col-md-6">
            <h3>With Your Friends</h3>
            <ul>
                <li>Improve your friendship by discovering your strengths and areas for improvement</li>
                <li>Let your friends be honest with you</li>
            </ul>
        </div>
    </div>
    <br>
    <p><a href="#">Login</a> | <a href="#">Register</a></p>
</div>
{% endblock %}