sarahah/accounts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout


from .views import dashboard, register, settings, editProfile, changePassword, removeProfile

urlpatterns = [
    url(r'^$', dashboard, name="dashboard"),
    url(r'^login/$', login, {'template_name':'accounts/login.html'}, name="login"),
    url(r'^logout/$', logout, {'next_page':'core:home'}, name="logout"),
    url(r'^register/', register, name="register"),
    url(r'^settings/(?P<setting>[\w]+)/', settings, name="settings"),

    url(r'^edit/', editProfile, name="editProfile"),
    url(r'^cgdPassword/', changePassword, name="changePassword"),
    url(r'^rmvProfile/', removeProfile, name="removeProfile"),
]

sarahah/smessages/urls.py
from django.conf.urls import url, include

from .views import favoriteMessage, deleteMessage


urlpatterns = [
    url(r'favorite/(?P<idMessage>[\w0-9_-]+)/', favoriteMessage, name='favorite'),
    url(r'delete/(?P<idMessage>[\w0-9_-]+)/', deleteMessage, name='delete'),
]

sarahah/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from sarahah.core import urls as core
from sarahah.accounts import urls as accounts
from sarahah.smessages import urls as messages

from sarahah.accounts.views import pubProfile

urlpatterns = [
    url(r'', include(core, namespace="core")),
    url(r'^admin/', admin.site.urls),
    url(r'accounts/', include(accounts, namespace="account")),
    url(r'messages/', include(messages, namespace="message")),
    url(r'^(?P<profile>[\w0-9_-]+)/$', pubProfile, name='pubProfile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sarahah/accounts/models.py
import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.conf import settings

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Username', max_length=30, unique=True, validators=[
            validators.RegexValidator(re.compile('^[\w.@+-]+$'),
                                      "usuario pode contem somente letras, digitos ou @/./+/-/_", 'invalid')
        ]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Full Name', max_length=100, blank=True)

    is_active = models.BooleanField('Está Ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da Equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Cadastro', auto_now_add=True)

    profilePic = models.ImageField(
        upload_to='accounts/profiles', verbose_name='Profile picture',
        null=True, blank=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

sarahah/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model, password_validation

User = get_user_model()


class RegisterUserForm(forms.ModelForm):

    password1 = forms.CharField(
        label=("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )

    password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=("Enter the same password as before, for verification."),
    )

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    class Meta:
        model = User
        fields = ['username', 'name', 'email', 'profilePic']


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'email', 'profilePic')

class RemoveProfileForm(forms.Form):
    really = forms.BooleanField(
        label=("I'm sure I want to delete my account"),
        required=True,
        help_text=("Are you sure you want to delete your account?"),
    )

sarahah/smessages/forms.py
from django import forms

from .models import Messages

class SendMessage(forms.ModelForm):
    message = forms.CharField(
        label='Message',
        max_length=255,
        widget=forms.Textarea,
        help_text="You have 255 characters remainings"
    )

    class Meta:
        model = Messages
        fields = ('message',)

sarahah/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required

from .forms import RegisterUserForm, EditUserForm, RemoveProfileForm
from .models import User

from sarahah.smessages.forms import SendMessage
from sarahah.smessages.models import Messages

# Create your views here.


@login_required
def dashboard(request):
    template_name = "accounts/dashboard.html"
    received = request.user.received.all().order_by('-date_joined')
    send = request.user.sender.all().order_by('-date_joined')
    favorites = request.user.received.filter(favorite=True).order_by('-date_joined')

    context = {
        'received': received,
        'sender': send,
        'favorites': favorites
    }
    return render(request, template_name, context)


def register(request):
    template_name = "accounts/register.html"
    if request.method == "POST":
        form = RegisterUserForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['password1']
            )
            messages.success(
                request, 'Register now, just use our platform!')
            login(request, user)
            return redirect('account:dashboard')
    else:
        form = RegisterUserForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)


@login_required
def settings(request, setting):
    template_name = "accounts/settings.html"
    template = "accounts/security/_default.html"
    context = {}
    if setting == "profile":
        form = EditUserForm(instance=request.user)
        context['form'] = form
        template = "accounts/security/_" + setting + ".html"
    elif setting == "changePassword":
        form = PasswordChangeForm(request.user)
        context['form'] = form
        template = "accounts/security/_" + setting + ".html"
    elif setting == "removeProfile":
        form = RemoveProfileForm()
        context['form'] = form
        messages.warning(
            request, "Are you sure that you want to delete your account? Deleting the account is irreversible!"
        )
        template = "accounts/security/_" + setting + ".html"
    else:
        messages.error(request, "Error 404, area does not exist")

    context['template'] = template
    context['setting'] = setting
    return render(request, template_name, context)


@login_required
def editProfile(request):
    if request.method == "POST":
        form = EditUserForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile successfully edited")
            return redirect('account:dashboard')
    else:
        messages.error(request, "Error 404, Not accessible method")


@login_required
def changePassword(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('account:dashboard')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        messages.error(request, "Error 404, Not accessible method")


@login_required
def removeProfile(request):
    if request.method == "POST":
        form = RemoveProfileForm(request.POST)
        user = get_object_or_404(User, pk=request.user.pk)
        if form.is_valid():
            logout(request)
            user.delete()
            messages.success(request, '')
            return redirect('core:home')
    else:
        messages.error(request, "Error 404, Not accessible method")


def pubProfile(request, profile):
    template_name = "accounts/pubProfile.html"
    received = get_object_or_404(User, username=profile)

    if request.method == "POST":
        form = SendMessage(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.received = received
            if request.user.is_authenticated  :
                form.sender = request.user
            else:
                form.sender = User.objects.all()[0]
            form.save()
            messages.success(
                request, 'Message sent successfully!')
            return redirect('pubProfile', received.username)
    else:
        form = SendMessage()

    context = {
        'received': received,
        'form': form
    }
    return render(request, template_name, context)

sarahah/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
{% load bootstrap3 %}
<div class="container">
    {% bootstrap_messages %}
    <div class="panel panel-default">
        <div class="panel-body text-center">
            <p><img src="{{ user.profilePic.url }}" alt="{{ user.username }}" class="img-circle img-profile"></p>
            <p><a href="{% url 'account:settings' 'profile' %}"><i class="fa fa-cog" aria-hidden="true"></i></a> <b>{{ user.name | title}}</b></p>
            <p><b>Messages: </b></p>
            <p><a href="{% url 'pubProfile' user.username %}">https://sarahah.com/{{ user.username }}/</a></p>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="text-center">
                <h2> <i class="fa fa-comments" aria-hidden="true"></i> Messages</h2>
            </div>
            <div>
                <br>
                <ul class="nav nav-tabs nav-justified">
                    <li class="active"><a data-toggle="tab" href="#received">Received</a></li>
                    <li><a data-toggle="tab" href="#favorites">Favorites</a></li>
                    <li><a data-toggle="tab" href="#sent">Sent</a></li>
                </ul>

                <div class="tab-content">
                    <div id="received" class="tab-pane fade in active">
                        {% for message in received %}
                        <br>
                        <div class="panel panel-default">
                            <div class="panel-body row">
                                <div class="col col-sm-10">
                                    <p>{{message.message}}</p>
                                    <br>
                                </div>
                                <div class="col col-sm-2 text-right">
                                    <form method="post" action="{% url 'message:delete' message.pk %}" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-default"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                    </form>
                                </div>
                                <div class="col col-sm-10">
                                    <p class="text-muted">{{ message.date_joined }}</p>
                                </div>
                                <div class="col col-sm-2 text-right">
                                    <form method="post" action="{% url 'message:favorite' message.pk %}" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-default"><i class="fa fa-heart" aria-hidden="true"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <br>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <p>Nothing to Show, share your page to others persons sent messages to you</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div id="favorites" class="tab-pane fade">
                        {% for message in favorites %}
                        <br>
                        <div class="panel panel-default">
                            <div class="panel-body row">
                                <div class="col col-sm-10">
                                    <p>{{message.message}}</p>
                                    <br>
                                </div>
                                <div class="col col-sm-2 text-right">
                                    <form method="post" action="{% url 'message:delete' message.pk %}" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-default"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                    </form>
                                </div>
                                <div class="col col-sm-10">
                                    <p class="text-muted">{{ message.date_joined }}</p>
                                </div>
                                <div class="col col-sm-2 text-right">
                                    <form method="post" action="{% url 'message:favorite' message.pk %}" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-default"><i class="fa fa-heart" aria-hidden="true"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <br>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <p>Nothing to Show, share your page to others persons sent messages to you</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div id="sent" class="tab-pane fade">
                        {% for message in sender %}
                        <br>
                        <div class="panel panel-default">
                            <div class="panel-body row">
                                <div class="col col-sm-10">
                                    <p>{{message.message}}</p>
                                    <br>
                                </div>
                                <div class="col col-sm-2 text-right">
                                    <form method="post" action="{% url 'message:delete' message.pk %}" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-default"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                    </form>
                                </div>
                                <div class="col col-sm-10">
                                    <p class="text-muted">{{ message.date_joined }}</p>
                                </div>
                                <div class="col col-sm-2 text-right">
                                    <form method="post" action="{% url 'message:favorite' message.pk %}" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-default"><i class="fa fa-heart" aria-hidden="true"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                        <br>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <p>Nothing to Show, share your page to others persons sent messages to you</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sarahah/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
- Login
{% endblock %}

{% block content %}

<div class="row">
    <div class="col col-sm-12 col-md-4 col-md-offset-4">
        {% if request.user.is_authenticated %}
        <h2>Você ja esta logado, por favor vá para a pagina inicial</h2>
        <p><a href="{% url 'core:home' %}" class="btn btn-warning">Pagina Inicial</a></p>
        {% else %}
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Login</h3>
            </div>
            <div class="panel-body">
                {% bootstrap_messages %}
                <form method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <br>
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            Send {% bootstrap_icon "send" %}
                        </button>
                    {% endbuttons %}
                </form>
                <br>
                <p><b>Esqueceu sua senha?</b> <a href="">Recuperar Senha</a> </p>
                <p><b>Novo por aqui?</b> <a href="">Inscrever-se</a> </p>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

sarahah/accounts/templates/accounts/pubProfile.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
{% load bootstrap3 %}
<div class="container">
    {% bootstrap_messages %}
    <div class="panel panel-default">
        <div class="panel-body text-center">
            <p><img src="{{ received.profilePic.url }}" alt="{{ received.username }}" class="img-circle img-profile"></p>
            <p><b>{{ received.name | title}}</b></p>
            <p>Leave a constructive message :)</p>
            <hr>
            <div class="row">
                <div class="col col-sm-12 col-md-6 col-md-offset-3">
                    <form method="POST">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <br>
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                Send {% bootstrap_icon "send" %}
                            </button>
                        {% endbuttons %}
                    </form>  
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).on("input", "#id_message", function () {
        var limite = 255;
        var caracteresDigitados = $(this).val().length;
        var caracteresRestantes = limite - caracteresDigitados;

        $(".help-block").text("You have "+caracteresRestantes+" characters remainings");
    });
</script>
{% endblock %}

sarahah/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
- Registrar-se
{% endblock %}

{% block content %}

<div class="row">
    <div class="col col-sm-12 col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Formulário de Registro</h3>
            </div>
            <div class="panel-body">
                {% bootstrap_messages %}
                <form method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <br>
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">
                            Cadastrar {% bootstrap_icon "send" %}
                        </button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

sarahah/accounts/templates/accounts/settings.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col col-sm-12 col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Settings</h3>
                </div>
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li role="presentation" {% if setting == "profile" %} class="active" {% endif %}><a href="{% url 'account:settings' 'profile' %}"><i class="fa fa-user" aria-hidden="true"></i> Personal Information</a></li>
                        <li role="presentation" {% if setting == "changePassword" %} class="active" {% endif %}><a href="{% url 'account:settings' 'changePassword' %}"><i class="fa fa-lock" aria-hidden="true"></i> Password</a></li>
                        <li role="presentation" {% if setting == "removeProfile" %} class="active" {% endif %}><a href="{% url 'account:settings' 'removeProfile' %}"><i class="fa fa-user-times" aria-hidden="true"></i> Remove Account</a></li>
                        <li role="presentation"><a href="{% url 'account:dashboard' %}"><i class="fa fa-comments" aria-hidden="true"></i> Back to Messages</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col col-sm-12 col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% bootstrap_messages %}
                    {% include template %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}